<a href="https://colab.research.google.com/github/m-tahamansoor/ML-task-1/blob/main/Data%20Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries

In [3]:
import numpy as np
import pandas as pd

Entering Data

In [58]:
Data ={
    'Employee ID': [1, 2, 3, 4, np.nan, 6, 7, 8, np.nan, 10, 11],
    'Name': ['Muhammad Taha Mansoor', 'Aleeza Asghar', 'Awais Mushtaq', 'Eraj Jamil', 'Abdullah Ehsan', 'Hunniyah Jahangir', 'Muhammad Ehtesham', 'Moez Ul Haq', 'Fraz Rasool', 'Talha Ahmad Siddiqui', 'Abdul Rehman Ali'],
    'Age': [21, 20, 22, 21, 20, np.nan, 19, 20, 18, np.nan, 20],
    'Email': ['taha@gmail.com', 'aleeza@gmail.com', 'awais@gmail.com', 'np.nan', 'abdullah@gmail.com', 'hunniyah@gmail.com', 'ehtesham@gmail.com', 'moez@gmail.com', 'fraz@gmail.com', 'talha@gmail.com', np.nan],
    'Address': ['I-10', 'Kachee Tendon Wala Hostel', 'E-11', 'Thande Pani Wala Hostel', 'F-17', np.nan, 'Ameeron Wala Hostel', 'G-11', 'E-11 Hostel', np.nan, 'Namaloom Jagah'],
    'Projects': [3, 5, 7, 5, np.nan, 5, 7, 5, 3, np.nan, 7],
    'Salary': ['30000', '50000','70000', '50000', '30000', '50000', np.nan, '50000', '30000', '50000', '70000'],
    'Year of Experience': [2, 3, 4, np.nan, 2, 2, 2, np.nan, 2, 2, 2]
}
df = pd.DataFrame(Data)
df

,Employee ID,Name,Age,Email,Address,Projects,Salary,Year of Experience
0,1.0,Muhammad Taha Mansoor,21.0,taha@gmail.com,I-10,3.0,30000,2.0
1,2.0,Aleeza Asghar,20.0,aleeza@gmail.com,Kachee Tendon Wala Hostel,5.0,50000,3.0
2,3.0,Awais Mushtaq,22.0,awais@gmail.com,E-11,7.0,70000,4.0
3,4.0,Eraj Jamil,21.0,np.nan,Thande Pani Wala Hostel,5.0,50000,NaN
4,NaN,Abdullah Ehsan,20.0,abdullah@gmail.com,F-17,NaN,30000,2.0
5,6.0,Hunniyah Jahangir,NaN,hunniyah@gmail.com,NaN,5.0,50000,2.0
6,7.0,Muhammad Ehtesham,19.0,ehtesham@gmail.com,Ameeron Wala Hostel,7.0,NaN,2.0
7,8.0,Moez Ul Haq,20.0,moez@gmail.com,G-11,5.0,50000,NaN
8,NaN,Fraz Rasool,18.0,fraz@gmail.com,E-11 Hostel,3.0,30000,2.0
9,10.0,Talha Ahmad Siddiqui,NaN,talha@gmail.com,NaN,NaN,50000,2.0
10,11.0,Abdul Rehman Ali,20.0,NaN,Namaloom Jagah,7.0,70000,2.0

Mean Imputation

In [59]:
df['imputed_mean_age'] = df['Age'].fillna(df['Age'].mean())
df

,Employee ID,Name,Age,Email,Address,Projects,Salary,Year of Experience,imputed_mean_age
0,1.0,Muhammad Taha Mansoor,21.0,taha@gmail.com,I-10,3.0,30000,2.0,21.000000
1,2.0,Aleeza Asghar,20.0,aleeza@gmail.com,Kachee Tendon Wala Hostel,5.0,50000,3.0,20.000000
2,3.0,Awais Mushtaq,22.0,awais@gmail.com,E-11,7.0,70000,4.0,22.000000
3,4.0,Eraj Jamil,21.0,np.nan,Thande Pani Wala Hostel,5.0,50000,NaN,21.000000
4,NaN,Abdullah Ehsan,20.0,abdullah@gmail.com,F-17,NaN,30000,2.0,20.000000
5,6.0,Hunniyah Jahangir,NaN,hunniyah@gmail.com,NaN,5.0,50000,2.0,20.111111
6,7.0,Muhammad Ehtesham,19.0,ehtesham@gmail.com,Ameeron Wala Hostel,7.0,NaN,2.0,19.000000
7,8.0,Moez Ul Haq,20.0,moez@gmail.com,G-11,5.0,50000,NaN,20.000000
8,NaN,Fraz Rasool,18.0,fraz@gmail.com,E-11 Hostel,3.0,30000,2.0,18.000000
9,10.0,Talha Ahmad Siddiqui,NaN,talha@gmail.com,NaN,NaN,50000,2.0,20.111111
10,11.0,Abdul Rehman Ali,20.0,NaN,Namaloom Jagah,7.0,70000,2.0,20.000000

Medium Imputation

In [60]:
df['imputed_medium_age'] = df['Age'].fillna(df['Age'].median())
df

,Employee ID,Name,Age,Email,Address,Projects,Salary,Year of Experience,imputed_mean_age,imputed_medium_age
0,1.0,Muhammad Taha Mansoor,21.0,taha@gmail.com,I-10,3.0,30000,2.0,21.000000,21.0
1,2.0,Aleeza Asghar,20.0,aleeza@gmail.com,Kachee Tendon Wala Hostel,5.0,50000,3.0,20.000000,20.0
2,3.0,Awais Mushtaq,22.0,awais@gmail.com,E-11,7.0,70000,4.0,22.000000,22.0
3,4.0,Eraj Jamil,21.0,np.nan,Thande Pani Wala Hostel,5.0,50000,NaN,21.000000,21.0
4,NaN,Abdullah Ehsan,20.0,abdullah@gmail.com,F-17,NaN,30000,2.0,20.000000,20.0
5,6.0,Hunniyah Jahangir,NaN,hunniyah@gmail.com,NaN,5.0,50000,2.0,20.111111,20.0
6,7.0,Muhammad Ehtesham,19.0,ehtesham@gmail.com,Ameeron Wala Hostel,7.0,NaN,2.0,19.000000,19.0
7,8.0,Moez Ul Haq,20.0,moez@gmail.com,G-11,5.0,50000,NaN,20.000000,20.0
8,NaN,Fraz Rasool,18.0,fraz@gmail.com,E-11 Hostel,3.0,30000,2.0,18.000000,18.0
9,10.0,Talha Ahmad Siddiqui,NaN,talha@gmail.com,NaN,NaN,50000,2.0,20.111111,20.0
10,11.0,Abdul Rehman Ali,20.0,NaN,Namaloom Jagah,7.0,70000,2.0,20.000000,20.0

Mode Imputation

In [61]:
df['imputed_mode-YearOfExperience'] = df['Year of Experience'].fillna(df['Year of Experience'].mode()[0])
df

,Employee ID,Name,Age,Email,Address,Projects,Salary,Year of Experience,imputed_mean_age,imputed_medium_age,imputed_mode-YearOfExperience
0,1.0,Muhammad Taha Mansoor,21.0,taha@gmail.com,I-10,3.0,30000,2.0,21.000000,21.0,2.0
1,2.0,Aleeza Asghar,20.0,aleeza@gmail.com,Kachee Tendon Wala Hostel,5.0,50000,3.0,20.000000,20.0,3.0
2,3.0,Awais Mushtaq,22.0,awais@gmail.com,E-11,7.0,70000,4.0,22.000000,22.0,4.0
3,4.0,Eraj Jamil,21.0,np.nan,Thande Pani Wala Hostel,5.0,50000,NaN,21.000000,21.0,2.0
4,NaN,Abdullah Ehsan,20.0,abdullah@gmail.com,F-17,NaN,30000,2.0,20.000000,20.0,2.0
5,6.0,Hunniyah Jahangir,NaN,hunniyah@gmail.com,NaN,5.0,50000,2.0,20.111111,20.0,2.0
6,7.0,Muhammad Ehtesham,19.0,ehtesham@gmail.com,Ameeron Wala Hostel,7.0,NaN,2.0,19.000000,19.0,2.0
7,8.0,Moez Ul Haq,20.0,moez@gmail.com,G-11,5.0,50000,NaN,20.000000,20.0,2.0
8,NaN,Fraz Rasool,18.0,fraz@gmail.com,E-11 Hostel,3.0,30000,2.0,18.000000,18.0,2.0
9,10.0,Talha Ahmad Siddiqui,NaN,talha@gmail.com,NaN,NaN,50000,2.0,20.111111,20.0,2.0
10,11.0,Abdul Rehman Ali,20.0,NaN,Namaloom Jagah,7.0,70000,2.0,20.000000,20.0,2.0

Removing Rows

In [62]:
removing_rows = df.dropna()
removing_rows

,Employee ID,Name,Age,Email,Address,Projects,Salary,Year of Experience,imputed_mean_age,imputed_medium_age,imputed_mode-YearOfExperience
0,1.0,Muhammad Taha Mansoor,21.0,taha@gmail.com,I-10,3.0,30000,2.0,21.0,21.0,2.0
1,2.0,Aleeza Asghar,20.0,aleeza@gmail.com,Kachee Tendon Wala Hostel,5.0,50000,3.0,20.0,20.0,3.0
2,3.0,Awais Mushtaq,22.0,awais@gmail.com,E-11,7.0,70000,4.0,22.0,22.0,4.0

Forward Fill

In [64]:
df['Project_Forward_Fill'] = df['Projects'].fillna(method='ffill')
df

<ipython-input-64-dc71af778cee>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Project_Forward_Fill'] = df['Projects'].fillna(method='ffill')

,Employee ID,Name,Age,Email,Address,Projects,Salary,Year of Experience,imputed_mean_age,imputed_medium_age,imputed_mode-YearOfExperience,Project_Forward_Fill
0,1.0,Muhammad Taha Mansoor,21.0,taha@gmail.com,I-10,3.0,30000,2.0,21.000000,21.0,2.0,3.0
1,2.0,Aleeza Asghar,20.0,aleeza@gmail.com,Kachee Tendon Wala Hostel,5.0,50000,3.0,20.000000,20.0,3.0,5.0
2,3.0,Awais Mushtaq,22.0,awais@gmail.com,E-11,7.0,70000,4.0,22.000000,22.0,4.0,7.0
3,4.0,Eraj Jamil,21.0,np.nan,Thande Pani Wala Hostel,5.0,50000,NaN,21.000000,21.0,2.0,5.0
4,NaN,Abdullah Ehsan,20.0,abdullah@gmail.com,F-17,NaN,30000,2.0,20.000000,20.0,2.0,5.0
5,6.0,Hunniyah Jahangir,NaN,hunniyah@gmail.com,NaN,5.0,50000,2.0,20.111111,20.0,2.0,5.0
6,7.0,Muhammad Ehtesham,19.0,ehtesham@gmail.com,Ameeron Wala Hostel,7.0,NaN,2.0,19.000000,19.0,2.0,7.0
7,8.0,Moez Ul Haq,20.0,moez@gmail.com,G-11,5.0,50000,NaN,20.000000,20.0,2.0,5.0
8,NaN,Fraz Rasool,18.0,fraz@gmail.com,E-11 Hostel,3.0,30000,2.0,18.000000,18.0,2.0,3.0
9,10.0,Talha Ahmad Siddiqui,NaN,talha@gmail.com,NaN,NaN,50000,2.0,20.111111,20.0,2.0,3.0
10,11.0,Abdul Rehman Ali,20.0,NaN,Namaloom Jagah,7.0,70000,2.0,20.000000,20.0,2.0,7.0

Backward Fill

In [65]:
df['Salary_Backward_Fill'] = df['Salary'].fillna(method='bfill')
df

<ipython-input-65-030253630b52>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Salary_Backward_Fill'] = df['Salary'].fillna(method='bfill')

,Employee ID,Name,Age,Email,Address,Projects,Salary,Year of Experience,imputed_mean_age,imputed_medium_age,imputed_mode-YearOfExperience,Project_Forward_Fill,Salary_Backward_Fill
0,1.0,Muhammad Taha Mansoor,21.0,taha@gmail.com,I-10,3.0,30000,2.0,21.000000,21.0,2.0,3.0,30000
1,2.0,Aleeza Asghar,20.0,aleeza@gmail.com,Kachee Tendon Wala Hostel,5.0,50000,3.0,20.000000,20.0,3.0,5.0,50000
2,3.0,Awais Mushtaq,22.0,awais@gmail.com,E-11,7.0,70000,4.0,22.000000,22.0,4.0,7.0,70000
3,4.0,Eraj Jamil,21.0,np.nan,Thande Pani Wala Hostel,5.0,50000,NaN,21.000000,21.0,2.0,5.0,50000
4,NaN,Abdullah Ehsan,20.0,abdullah@gmail.com,F-17,NaN,30000,2.0,20.000000,20.0,2.0,5.0,30000
5,6.0,Hunniyah Jahangir,NaN,hunniyah@gmail.com,NaN,5.0,50000,2.0,20.111111,20.0,2.0,5.0,50000
6,7.0,Muhammad Ehtesham,19.0,ehtesham@gmail.com,Ameeron Wala Hostel,7.0,NaN,2.0,19.000000,19.0,2.0,7.0,50000
7,8.0,Moez Ul Haq,20.0,moez@gmail.com,G-11,5.0,50000,NaN,20.000000,20.0,2.0,5.0,50000
8,NaN,Fraz Rasool,18.0,fraz@gmail.com,E-11 Hostel,3.0,30000,2.0,18.000000,18.0,2.0,3.0,30000
9,10.0,Talha Ahmad Siddiqui,NaN,talha@gmail.com,NaN,NaN,50000,2.0,20.111111,20.0,2.0,3.0,50000
10,11.0,Abdul Rehman Ali,20.0,NaN,Namaloom Jagah,7.0,70000,2.0,20.000000,20.0,2.0,7.0,70000

Interpolation

In [67]:
id_interpolation = df['Employee ID'].interpolate(method='linear')
df
#unable to print id_interpolation column

,Employee ID,Name,Age,Email,Address,Projects,Salary,Year of Experience,imputed_mean_age,imputed_medium_age,imputed_mode-YearOfExperience,Project_Forward_Fill,Salary_Backward_Fill
0,1.0,Muhammad Taha Mansoor,21.0,taha@gmail.com,I-10,3.0,30000,2.0,21.000000,21.0,2.0,3.0,30000
1,2.0,Aleeza Asghar,20.0,aleeza@gmail.com,Kachee Tendon Wala Hostel,5.0,50000,3.0,20.000000,20.0,3.0,5.0,50000
2,3.0,Awais Mushtaq,22.0,awais@gmail.com,E-11,7.0,70000,4.0,22.000000,22.0,4.0,7.0,70000
3,4.0,Eraj Jamil,21.0,np.nan,Thande Pani Wala Hostel,5.0,50000,NaN,21.000000,21.0,2.0,5.0,50000
4,NaN,Abdullah Ehsan,20.0,abdullah@gmail.com,F-17,NaN,30000,2.0,20.000000,20.0,2.0,5.0,30000
5,6.0,Hunniyah Jahangir,NaN,hunniyah@gmail.com,NaN,5.0,50000,2.0,20.111111,20.0,2.0,5.0,50000
6,7.0,Muhammad Ehtesham,19.0,ehtesham@gmail.com,Ameeron Wala Hostel,7.0,NaN,2.0,19.000000,19.0,2.0,7.0,50000
7,8.0,Moez Ul Haq,20.0,moez@gmail.com,G-11,5.0,50000,NaN,20.000000,20.0,2.0,5.0,50000
8,NaN,Fraz Rasool,18.0,fraz@gmail.com,E-11 Hostel,3.0,30000,2.0,18.000000,18.0,2.0,3.0,30000
9,10.0,Talha Ahmad Siddiqui,NaN,talha@gmail.com,NaN,NaN,50000,2.0,20.111111,20.0,2.0,3.0,50000
10,11.0,Abdul Rehman Ali,20.0,NaN,Namaloom Jagah,7.0,70000,2.0,20.000000,20.0,2.0,7.0,70000